spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
      defer-datasource-initialization: true
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

server:
  error:
    include-message: always

JobSeekerApplication:
  http:
    auth-token-header-name: X-API-KEY
